version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./lumen:/app
      - ./docker/proxy/conf.d:/etc/nginx/conf.d
    links:
      - php:php
  php:
    build: ./docker/php
    volumes:
      - ./lumen:/app
    links:
      - mongo:mongo
      - redis:redis
  mongo:
    image: mongo:latest
  redis:
    image: redis:latest